version: "2.2"

services:
  nginx:
    image: tiangolo/nginx-rtmp
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - ./app:/usr/share/nginx/html
    #networks:
    ports:
      - "1935:1935"
      - "8080:8080"

